version: "3"
services:
  flinky:
    container_name: flinky
    image: flink:1.3
    volumes:
      - .\artifacts:/home/jar
      - .\data-in:/home/data-in
      - .\data-out:/home/data-out
    ports:
      - "8081:8081"
    command:
      - local